#encoding: latin-1

# libzzub, Buzé, Aldrin
# Modular Sequencer
# Copyright (C) 2006 The Aldrin Development Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Import('pluginenv', 'install_lib', 'cl', 'posix', 'build_plugin')

if cl and pluginenv['BUZZ2ZZUB'] == True:
	pluginenv.Append(LIBS=[
		'dsplib',
	])
	pluginenv.Append(CCFLAGS= [
		'-DUSE_PLUGIN_CACHE'
	])
	if posix:
		pluginenv['CXX'] = 'wineg++'
	build_plugin(pluginenv, 'buzz2zzub', [
		'buzz2zzub.cpp',
		'mdkimpl.cpp',
		'unhack.cpp',
		'MemoryModule.c',
	])
	install_lib('${ROOTPATH}/lib/dsplib.dll')
