// Common for mainframe and all views
#define ID_BLANK_STRING                 32838

// Preset dialog
#define IDD_PRESETS                     217
#define IDC_PRESET_NAME                 1063
#define IDC_PRESET_LIST                 1064
#define IDC_PRESET_DELETE_BUTTON        1065
#define IDC_PRESET_COMMENT_EDIT         1066

// Select midi controller dialog
#define IDD_LEARNMIDICONTROLLER         209
#define IDC_MIDI_VALUE_EDIT             1029
#define IDC_MIDI_CONTROLLER_EDIT        1034
#define IDC_MIDI_CHANNEL_EDIT           1035

// Parameter view
#define IDT_HELP_PARAMETERVIEW          1088
#define IDR_PARAMETERS                  215
#define IDC_PRESETDROPDOWN              1072

#define ID_PARAMETER_BIND               53874
#define ID_PARAMETER_UNBIND             53875
#define ID_PARAMETER_HIDE               53876
#define ID_PARAMETER_UNHIDE_FIRST       53877
#define ID_PARAMETER_UNHIDE_LAST        54005
#define ID_PARAMETERVIEW_NEXTSLIDER     53406
#define ID_PARAMETERVIEW_PREVIOUSSLIDER 53407
#define ID_PARAMETERVIEW_MOVERIGHT      53408
#define ID_PARAMETERVIEW_MOVESOMERIGHT  53409
#define ID_PARAMETERVIEW_MOVEPAGERIGHT  53410
#define ID_PARAMETERVIEW_MOVELEFT       53411
#define ID_PARAMETERVIEW_MOVESOMELEFT   53412
#define ID_PARAMETERVIEW_MOVEPAGELEFT   53413
#define ID_PARAMETERVIEW_ENTERVALUE     53414
#define ID_PARAMETERVIEW_PRESETS        53420
#define ID_PARAMETERVIEW_NEXTPRESET     53562
#define ID_PARAMETERVIEW_PREVIOUSPRESET 53563
#define ID_PARAMETERVIEW_PAGEUPSLIDER   53464
#define ID_PARAMETERVIEW_PAGEDOWNSLIDER 53465

#define ID_PRESET_EDIT                  52883
#define ID_PRESET_COPY                  52884
#define ID_PRESET_COPY_ALL              52885
#define ID_PRESET_COPY_GLOBAL           52886
#define ID_PRESET_COPY_TRACK            52887
#define ID_PRESET_RANDOMIZE             52888
#define ID_PRESET_HUMANIZE              56982
#define ID_PRESET_MODE                     57034
#define ID_PRESET_MACHINEHELP           40002
