/* autogenerated by zidl 2 */
#if !defined(__zzub_H)
#define __zzub_H

#if defined(__cplusplus)
extern "C" {
#endif


enum {
  zzub_version = 0xf,
  zzub_buffer_size = 0x100,
};

enum zzub_player_state {
  zzub_player_state_playing = 0x0,
  zzub_player_state_stopped = 0x1,
  zzub_player_state_muted = 0x2,
  zzub_player_state_released = 0x3,
};

enum zzub_parameter_type {
  zzub_parameter_type_note = 0x0,
  zzub_parameter_type_switch = 0x1,
  zzub_parameter_type_byte = 0x2,
  zzub_parameter_type_word = 0x3,
  zzub_parameter_type_meta = 0x4,
};

enum zzub_wave_buffer_type {
  zzub_wave_buffer_type_si16 = 0x0,
  zzub_wave_buffer_type_f32 = 0x1,
  zzub_wave_buffer_type_si32 = 0x2,
  zzub_wave_buffer_type_si24 = 0x3,
};

enum zzub_oscillator_type {
  zzub_oscillator_type_sine = 0x0,
  zzub_oscillator_type_sawtooth = 0x1,
  zzub_oscillator_type_pulse = 0x2,
  zzub_oscillator_type_triangle = 0x3,
  zzub_oscillator_type_noise = 0x4,
  zzub_oscillator_type_sawtooth_303 = 0x5,
};

enum zzub_note_value {
  zzub_note_value_none = 0x0,
  zzub_note_value_off = 0xff,
  zzub_note_value_cut = 0xfe,
  zzub_note_value_min = 0x1,
  zzub_note_value_max = 0x9c,
  zzub_note_value_c4 = 0x41,
};

enum zzub_switch_value {
  zzub_switch_value_none = 0xff,
  zzub_switch_value_off = 0x0,
  zzub_switch_value_on = 0x1,
};

enum zzub_wavetable_index_value {
  zzub_wavetable_index_value_none = 0x0,
  zzub_wavetable_index_value_min = 0x1,
  zzub_wavetable_index_value_max = 0xc8,
};

enum zzub_parameter_flag {
  zzub_parameter_flag_wavetable_index = 0x1,
  zzub_parameter_flag_state = 0x2,
  zzub_parameter_flag_event_on_edit = 0x4,
  zzub_parameter_flag_pattern_index = 0x8,
  zzub_parameter_flag_velocity_index = 0x10,
  zzub_parameter_flag_delay_index = 0x20,
  zzub_parameter_flag_compound = 0x40,
  zzub_parameter_flag_char_index = 0x80,
  zzub_parameter_flag_harmony_index = 0x100,
  zzub_parameter_flag_meta_note = 0x200,
  zzub_parameter_flag_meta_wave = 0x400,
};

enum zzub_plugin_flag {
  zzub_plugin_flag_plays_waves = 0x2,
  zzub_plugin_flag_uses_lib_interface = 0x4,
  zzub_plugin_flag_does_input_mixing = 0x10,
  zzub_plugin_flag_is_singleton = 0x8000,
  zzub_plugin_flag_is_root = 0x10000,
  zzub_plugin_flag_has_audio_input = 0x20000,
  zzub_plugin_flag_has_audio_output = 0x40000,
  zzub_plugin_flag_is_offline = 0x80000,
  zzub_plugin_flag_has_event_output = 0x100000,
  zzub_plugin_flag_stream = 0x400000,
  zzub_plugin_flag_has_midi_input = 0x800000,
  zzub_plugin_flag_has_midi_output = 0x1000000,
  zzub_plugin_flag_has_group_input = 0x2000000,
  zzub_plugin_flag_has_group_output = 0x4000000,
  zzub_plugin_flag_is_sequence = 0x8000000,
  zzub_plugin_flag_is_connection = 0x10000000,
  zzub_plugin_flag_is_interval = 0x20000000,
  zzub_plugin_flag_is_encoder = 0x40000000,
  zzub_plugin_flag_has_note_output = 0x80000000,
};

enum zzub_wave_flag {
  zzub_wave_flag_loop = 0x1,
  zzub_wave_flag_extended = 0x4,
  zzub_wave_flag_stereo = 0x8,
  zzub_wave_flag_pingpong = 0x10,
  zzub_wave_flag_envelope = 0x80,
};

enum zzub_envelope_flag {
  zzub_envelope_flag_sustain = 0x1,
  zzub_envelope_flag_loop = 0x2,
};

enum zzub_process_mode {
  zzub_process_mode_no_io = 0x0,
  zzub_process_mode_read = 0x1,
  zzub_process_mode_write = 0x2,
  zzub_process_mode_read_write = 0x3,
};

enum zzub_encoder_state {
  zzub_encoder_state_playing = 0x1,
  zzub_encoder_state_stopped = 0x2,
  zzub_encoder_state_deleted = 0x4,
  zzub_encoder_state_seeking = 0x8,
  zzub_encoder_state_created = 0x10,
};

enum zzub_connection_type {
  zzub_connection_type_audio = 0x0,
  zzub_connection_type_event = 0x1,
  zzub_connection_type_midi = 0x2,
  zzub_connection_type_note = 0x3,
};

enum zzub_parameter_group {
  zzub_parameter_group_internal = 0x0,
  zzub_parameter_group_global = 0x1,
  zzub_parameter_group_track = 0x2,
  zzub_parameter_group_controller = 0x3,
  zzub_parameter_group_virtual = 0x4,
};

#if defined(__cplusplus)
} // extern "C"
#endif

#endif // __zzub_H
